easy_admin:

  site_name: Conference Guestbook

  entities:
    Anno:
      class: App\Entity\Anno

    SeccionContenidos:
      class: App\Entity\SeccionContenidos

    Contenido:
      class: App\Entity\Contenido

    Usuario:
      class: App\Entity\Usuario

    Asignatura:
      class: App\Entity\Asignatura

    Administrador:
      class: App\Entity\Administrador

    Estudiante:
      class: App\Entity\Estudiante

    Profesor:
      class: App\Entity\Profesor

    Solicitud:
      class: App\Entity\Solicitud